import './src/styles/global.css';
import '@fontsource/noto-sans-jp';
import '@fontsource/noto-sans-jp/100.css';
import '@fontsource/noto-sans-jp/300.css';
import '@fontsource/noto-sans-jp/500.css';
import '@fontsource/noto-sans-jp/700.css';
import '@fontsource/noto-sans-jp/900.css';
import '@fontsource/vollkorn';
import '@fontsource/vollkorn/700.css';
